# '{pattern}' = '{icon}'

fallback = ''

[matching]
'discord' = ''
'/Discord/' = ''
'/WebCord/' = ''
'balena-etcher' = ''
'Chia Blockchain' = ''
'Steam' = ''
'vlc' = ''
'org.qbittorrent.qBittorrent' = ''
'Thunderbird' = ''
'thunderbird' = ''
'Postman' = ''
'Insomnia' = ''
'Bitwarden' = ''
'Google-chrome' = ''
'chromium' = ''
'Slack' = ''
'/(?i)Code/' = ''
'code-oss' = ''
'jetbrains-studio' = ''
'Spotify' = ''
'GitHub Desktop' = ''
'/(?i)Github.*Firefox/' = ''
'firefox' = ''
'Nightly' = ''
'firefoxdeveloperedition' = ''
'/nvim ?\w*/' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
'Alacritty' = ''
'kitty' = ''
'org.keepassxc.KeePassXC' = ''
'jetbrains-idea-ce' = ''
'parsecd' = ''
'/QEMU/' = ''
'sublime_text' = ''
'code-url-handler' = ''
'imv' = ''
'org.wireshark.Wireshark' = ''
'org.inkscape.Inkscape' = ''
'GNU Image Manipulation Program' = ''
'nemo' = ''
'Mysql-workbench-bin' = ''
'libreoffice-writer' = ''
'org.qt-project.qtcreator' = ''
'spicy' = ''
